import { Staatliches, Urbanist , Zilla_Slab_Highlight, Kaushan_Script } from "next/font/google";
import "./globals.css";

const staatliches = Staatliches({
  variable: "--font-staatliches",
  subsets: ["latin"],
  weight: ['400'],
  display: 'swap',
});

const urbanist = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
  weight: ['100' , '200' ,'300', '400', '500' , '600' , '700', '800' , '900'],
  display: 'swap',
});

const zillaSlabHighlight = Zilla_Slab_Highlight({
  variable: "--font-zilla_slab_highlight",
  subsets: ["latin"],
  weight: [ '400', '700'],
  display: 'swap',
});
const kaushanScript = Kaushan_Script({
  variable: "--font-kaushan-script",
  subsets: ["latin"],
  weight: [ '400'],
  display: 'swap',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${staatliches.variable} ${urbanist.variable} ${zillaSlabHighlight.variable} ${kaushanScript.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
